### create 
post http://localhost:3000/all_products
Content-Type: application/json

{
  "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-pro-max-graphite-select?",
  "product_id": "1"
}

### index
GET  http://localhost:3000/all_products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDI3Mjk2MzJ9.P3DkDw3JQs4ExUD-GuKk5np7DoxnvLdOv3H3txJf-xE


### show
GET   http://localhost:3000/all_products/1

### update
PATCH http://localhost:3000/all_products/4
Content-Type: application/json

{
   "price": "-1"
}

### delete
DELETE   http://localhost:3000/all_products/id=3

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "thirdTest name",
  "email": "thirdtest@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}


### create (orders)
POST http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDI4MTUxNzd9.d69vVZkslHHH9XiYo_cqTVEZczU_Rpfqhmmec1ydKdU
Content-Type: application/json

{
  "product_id": 2,
  "quantity": 3
}

### show (orders)
get http://localhost:3000/orders/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDI4MTUxNzd9.d69vVZkslHHH9XiYo_cqTVEZczU_Rpfqhmmec1ydKdU

### index (orders)
get http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDI4MTUxNzd9.d69vVZkslHHH9XiYo_cqTVEZczU_Rpfqhmmec1ydKdU