### create 
post http://localhost:3000/all_products
Content-Type: application/json

{
  "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-pro-max-graphite-select?",
  "product_id": "1"
}

### index
GET  http://localhost:3000/all_products


### show
GET   http://localhost:3000/all_products/1

### update
PATCH http://localhost:3000/all_products/4
Content-Type: application/json

{
   "price": "-1"
}

### delete
DELETE   http://localhost:3000/all_products/id=3